package com.crossBoard.repositoryTests.jdbcTests

import com.crossBoard.domain.*
import com.crossBoard.repository.interfaces.UserRepository
import com.crossBoard.repository.jdbc.JdbcUserRepo
import org.junit.jupiter.api.*
import org.postgresql.ds.PGSimpleDataSource
import org.testcontainers.containers.PostgreSQLContainer
import org.testcontainers.junit.jupiter.Container
import org.testcontainers.junit.jupiter.Testcontainers
import javax.sql.DataSource
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

@Testcontainers
class JdbcUserRepoTests {
    private lateinit var userRepo: UserRepository

    companion object {
        @Container
        @JvmStatic
        private val postgresContainer = PostgreSQLContainer("postgres:15-alpine")

        private lateinit var dataSource: DataSource

        @BeforeAll
        @JvmStatic
        fun `setup database and schema`() {
            val ds = PGSimpleDataSource().apply {
                setUrl(postgresContainer.jdbcUrl)
                user = postgresContainer.username
                password = postgresContainer.password
            }
            dataSource = ds

            val schemaSql = javaClass.getResource("/createTable.sql")!!.readText()
            dataSource.connection.use { it.createStatement().execute(schemaSql) }
        }
    }

    @BeforeEach
    fun `setup repository and clear data`() {
        userRepo = JdbcUserRepo(dataSource)

        dataSource.connection.use { conn ->
            conn.createStatement().execute("DELETE FROM match")
            conn.createStatement().execute("DELETE FROM users")
        }
    }

    @Test
    fun `addUser should create a user and return it with a generated ID`() {
        val username = Username("johndoe")
        val email = Email("john@doe.com")
        val password = Password("Aa12345!")

        val createdUser = userRepo.addUser(username, email, password)

        assertNotNull(createdUser)
        assertTrue(createdUser.id > 0, "ID should be generated by the database")
        assertEquals(username, createdUser.username)
        assertEquals(email, createdUser.email)
        assertNotNull(createdUser.token.value)
        assertTrue(createdUser is NormalUser)
    }

    @Test
    fun `getUserProfileById should return user info for existing user`() {
        val createdUser = userRepo.addUser(Username("testuser"), Email("test@user.com"), Password("Aa12345!"))

        val foundUser = userRepo.getUserProfileById(createdUser.id)

        assertNotNull(foundUser)
        assertEquals(createdUser.id, foundUser.id)
        assertEquals("testuser", foundUser.username.value)
    }

    @Test
    fun `getUserProfileById should return null for non-existent user`() {
        val foundUser = userRepo.getUserProfileById(9999)
        assertNull(foundUser)
    }

    @Test
    fun `getUserProfileByEmail should return user info`() {
        val email = Email("findme@example.com")
        userRepo.addUser(Username("findme"), email, Password("Aa12345!"))

        val foundUser = userRepo.getUserProfileByEmail(email)

        assertNotNull(foundUser)
        assertEquals(email, foundUser.email)
    }

    @Test
    fun `deleteUser should remove the user from the database`() {
        val userToDelete = userRepo.addUser(Username("deleteme"), Email("delete@me.com"), Password("Aa12345!"))

        val result = userRepo.deleteUser(userToDelete.id)

        assertTrue(result)
        val foundUser = userRepo.getUserProfileById(userToDelete.id)
        assertNull(foundUser, "User should not be found after deletion.")
    }

    @Test
    fun `updateUser should change username and state`() {
        val originalUser = userRepo.addUser(Username("original"), Email("original@test.com"), Password("Aa12345!"))
        val newUsername = Username("updated")
        val newState = UserState.BANNED

        val updatedInfo = userRepo.updateUser(originalUser.id, newUsername, null, null, newState)

        assertEquals(newUsername, updatedInfo.username)
        assertEquals(newState.name, updatedInfo.state)

        val fetchedUser = userRepo.getUserProfileById(originalUser.id)

        assertNotNull(fetchedUser)
        assertEquals(newUsername, fetchedUser.username)
        assertEquals(newState.name, fetchedUser.state)
        assertEquals(originalUser.email, fetchedUser.email)
    }

    @Test
    fun `getUsersByName should return users matching a prefix`() {
        userRepo.addUser(Username("testuser1"), Email("test1@test.com"), Password("Aa12345!"))
        userRepo.addUser(Username("testuser2"), Email("test2@test.com"), Password("Aa12345!"))
        userRepo.addUser(Username("anotheruser"), Email("another@test.com"), Password("Aa12345!"))

        val users = userRepo.getUsersByName("test", 0, 10)

        assertEquals(2, users.size)
        assertTrue(users.all { it.username.value.startsWith("test") })
    }

    @Test
    fun `getUsersByName should respect limit and skip parameters`() {
        for (i in 1..10) {
            userRepo.addUser(Username("user$i"), Email("user$i@test.com"), Password("Aa12345!"))
        }

        val users = userRepo.getUsersByName("user", 5, 3) // Skip 5, take 3

        assertEquals(3, users.size)
        assertEquals("user6", users[0].username.value)
        assertEquals("user7", users[1].username.value)
        assertEquals("user8", users[2].username.value)
    }
}