[versions]
agp = "8.10.0-alpha05"
android-compileSdk = "35"
android-minSdk = "25"
android-targetSdk = "35"
androidx-activityCompose = "1.10.1"

jdbi3Core = "3.32.0"
jdbi3Kotlin = "3.28.0"
junit = "4.13.2"
junitJupiter = "1.19.7"
kotlin = "2.1.10"
kotlinx-coroutines = "1.10.2"
kotlinxBrowser = "0.3"
kotlinxSerializationJson = "1.8.0"
ktor = "3.1.1"
lifecycleViewmodelCompose = "2.8.2"
logback = "1.5.16"
multiplatformSettingsVersion = "1.3.0"
postgresql = "42.5.0"
slf4jNop = "2.0.7"

voyager = "1.1.0-beta02"
ktorOpenAPIVersion = "5.0.2"
coilComposeCore = "3.2.0"

jetbrainsCompose = "1.8.2"

androidUi = "1.8.3"
wearCompose = "1.4.1"
[libraries]
jdbi3-core = { module = "org.jdbi:jdbi3-core", version.ref = "jdbi3Core" }
jdbi3-kotlin = { module = "org.jdbi:jdbi3-kotlin", version.ref = "jdbi3Kotlin" }
jdbi3-postgres = { module = "org.jdbi:jdbi3-postgres", version.ref = "jdbi3Core" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "junitJupiter" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-tests = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets-jvm", version.ref = "ktor" }
ktor-server-cors = {module = "io.ktor:ktor-server-cors-jvm", version.ref = "ktor"}
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-openapi = { module = "io.github.smiley4:ktor-openapi", version.ref = "ktorOpenAPIVersion"}
ktor-server-sse = { module = "io.ktor:ktor-server-sse", version.ref = "ktor"}

ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor"}
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor"}
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor"}
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor"}

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coilComposeCore" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coilComposeCore" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilComposeCore" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilComposeCore" }

multiplatform-settings-v130 = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettingsVersion" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4jNop" }

testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "junitJupiter" }

androidx-ui-text-android = { group = "androidx.compose.ui", name = "ui-text-android", version.ref = "androidUi" }
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "wearCompose" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "androidUi" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
coilBundle = [
    "coil",
    "coil-network-ktor",
    "coil-compose-core",
    "coil-compose"
]

ktorServer = [
    "ktor-server-content-negotiation",
    "ktor-serialization-kotlinx-json",
]

ktorClient = [
    "ktor-serialization-kotlinx-json",
    "ktor-client-content-negotiation",
    "ktor-client-logging",
    "ktor-client-core"
]